language: php
php:
 - "7.0"
 - "5.6"
 - "5.5"
 - "5.4"
 - "5.3"

matrix:
 fast_finish: true

os:
 - linux

before_script:
 - git clone git://github.com/jedisct1/libsodium.git
 - cd libsodium
 - ./autogen.sh
 - ./configure --disable-dependency-tracking --enable-minimal
 - make
 - sudo make install
 - sudo /sbin/ldconfig
 - cd ..
 - rm -fr libsodium

script:
 - phpize
 - ./configure --with-libsodium
 - make clean
 - make
 - env NO_INTERACTION=1 make test
